#!/usr/bin/env python3
"""
IRIS 작업 감사 추적(Audit Trail) HTML 생성기.

사용법:
    python generate_audit_trail.py --output /path/to/output.html --json /path/to/steps.json

또는 Python에서 직접 호출:
    from generate_audit_trail import AuditTrail
    trail = AuditTrail(task_summary="연구비 지급현황 조회", user="홍길동")
    trail.add_step("nav", "워크라운지 > 마이R&D에서 과제수행 > 연구비 > 연구비 지급현황으로 이동")
    trail.add_step("search", "과제번호 RS-2024-00123456로 검색, 결과 1건")
    trail.add_step("read", "연구비 지급현황: 정부출연금 50,000,000원, 집행액 32,000,000원")
    html = trail.render()
    trail.save("/path/to/output.html")
"""

import json
import sys
import argparse
from datetime import datetime
from pathlib import Path

# 단계 유형별 CSS 클래스와 한국어 태그 이름
STEP_TYPES = {
    "nav":     {"css": "step-nav",     "tag_css": "tag-nav",     "label": "네비게이션"},
    "search":  {"css": "step-search",  "tag_css": "tag-search",  "label": "검색"},
    "read":    {"css": "step-read",    "tag_css": "tag-read",    "label": "데이터 조회"},
    "input":   {"css": "step-input",   "tag_css": "tag-input",   "label": "입력"},
    "submit":  {"css": "step-submit",  "tag_css": "tag-submit",  "label": "제출"},
    "error":   {"css": "step-error",   "tag_css": "tag-error",   "label": "오류"},
    "resolve": {"css": "step-resolve", "tag_css": "tag-resolve", "label": "해결"},
    "info":    {"css": "step-info",    "tag_css": "tag-info",    "label": "참고"},
}

HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="ko">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>IRIS 작업 감사 추적 - {task_summary}</title>
<style>
  * {{ box-sizing: border-box; }}
  body {{
    font-family: 'Pretendard', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
    max-width: 900px; margin: 2rem auto; padding: 0 1rem;
    color: #1a1a2e; background: #f8f9fc; line-height: 1.6;
  }}
  h1 {{ color: #16213e; border-bottom: 3px solid #0f3460; padding-bottom: 0.5rem; font-size: 1.5rem; }}
  h2 {{ color: #0f3460; font-size: 1.15rem; margin-top: 2rem; }}

  .meta {{
    background: #fff; padding: 1rem 1.25rem; border-radius: 8px;
    margin: 1rem 0; border: 1px solid #e2e8f0;
    display: grid; grid-template-columns: auto 1fr; gap: 0.3rem 1rem;
  }}
  .meta dt {{ font-weight: 600; color: #0f3460; white-space: nowrap; }}
  .meta dd {{ margin: 0; }}

  .step {{
    border-left: 3px solid #cbd5e1; padding: 0.6rem 1rem; margin: 0.5rem 0;
    background: #fff; border-radius: 0 8px 8px 0; border: 1px solid #e2e8f0; border-left-width: 3px;
  }}
  .step p {{ margin: 0.3rem 0 0 0; }}

  .step-nav     {{ border-left-color: #3b82f6; }}
  .step-search  {{ border-left-color: #10b981; }}
  .step-read    {{ border-left-color: #f59e0b; }}
  .step-input   {{ border-left-color: #8b5cf6; }}
  .step-submit  {{ border-left-color: #ef4444; }}
  .step-error   {{ border-left-color: #ef4444; background: #fff5f5; }}
  .step-resolve {{ border-left-color: #10b981; background: #f0fdf4; }}
  .step-info    {{ border-left-color: #6b7280; }}

  .tag {{
    display: inline-block; padding: 1px 8px; border-radius: 4px;
    font-size: 0.78rem; font-weight: 600; margin-right: 6px; vertical-align: middle;
  }}
  .tag-nav     {{ background: #dbeafe; color: #1e40af; }}
  .tag-search  {{ background: #d1fae5; color: #065f46; }}
  .tag-read    {{ background: #fef3c7; color: #92400e; }}
  .tag-input   {{ background: #ede9fe; color: #5b21b6; }}
  .tag-submit  {{ background: #fee2e2; color: #991b1b; }}
  .tag-error   {{ background: #fecaca; color: #991b1b; }}
  .tag-resolve {{ background: #d1fae5; color: #065f46; }}
  .tag-info    {{ background: #f3f4f6; color: #374151; }}

  .timestamp {{ color: #94a3b8; font-size: 0.82rem; }}

  .result {{
    background: #fff; padding: 1rem 1.25rem; border-radius: 8px;
    margin: 1rem 0; border: 1px solid #d1fae5; border-left: 3px solid #10b981;
  }}
  .result-fail {{
    border-color: #fecaca; border-left-color: #ef4444;
  }}

  .footer {{
    margin-top: 2rem; padding-top: 1rem; border-top: 1px solid #e2e8f0;
    color: #94a3b8; font-size: 0.82rem; text-align: center;
  }}
</style>
</head>
<body>

<h1>IRIS 작업 감사 추적</h1>

<dl class="meta">
  <dt>작업 요약</dt><dd>{task_summary}</dd>
  <dt>수행 일시</dt><dd>{time_range}</dd>
  <dt>사용자</dt><dd>{user}</dd>
  <dt>결과</dt><dd>{result_status}</dd>
</dl>

<h2>수행 단계</h2>
{steps_html}

<h2>결과</h2>
<div class="result {result_class}">
{result_detail}
</div>

<div class="footer">
  Generated by IRIS Navigator Skill &middot; {generated_at}
</div>

</body>
</html>
"""

STEP_HTML = """\
<div class="step {step_css}">
  <span class="tag {tag_css}">{label}</span>
  <span class="timestamp">{timestamp}</span>
  <p>{description}</p>
</div>
"""


class AuditTrail:
    """IRIS 작업 감사 추적 기록기."""

    def __init__(self, task_summary: str, user: str = ""):
        self.task_summary = task_summary
        self.user = user
        self.start_time = datetime.now()
        self.end_time = None
        self.steps: list[dict] = []
        self.result_status = "진행 중"
        self.result_detail = ""
        self.success = True

    def add_step(self, step_type: str, description: str, timestamp: str | None = None):
        """
        감사 추적에 단계를 추가한다.

        Args:
            step_type: 단계 유형. "nav", "search", "read", "input", "submit",
                       "error", "resolve", "info" 중 하나.
            description: 수행한 동작에 대한 설명.
            timestamp: HH:MM:SS 형식의 시각. None이면 현재 시각 사용.
        """
        if step_type not in STEP_TYPES:
            step_type = "info"
        if timestamp is None:
            timestamp = datetime.now().strftime("%H:%M:%S")
        self.steps.append({
            "type": step_type,
            "description": description,
            "timestamp": timestamp,
        })

    def set_result(self, status: str, detail: str, success: bool = True):
        """
        최종 결과를 설정한다.

        Args:
            status: "성공", "실패", "부분 완료" 등.
            detail: 결과 상세 내용 (HTML 가능).
            success: 성공 여부.
        """
        self.end_time = datetime.now()
        self.result_status = status
        self.result_detail = detail
        self.success = success

    def render(self) -> str:
        """감사 추적 HTML을 생성하여 반환한다."""
        if self.end_time is None:
            self.end_time = datetime.now()

        # 단계 HTML 생성
        steps_parts = []
        for step in self.steps:
            info = STEP_TYPES.get(step["type"], STEP_TYPES["info"])
            steps_parts.append(STEP_HTML.format(
                step_css=info["css"],
                tag_css=info["tag_css"],
                label=info["label"],
                timestamp=step["timestamp"],
                description=_escape(step["description"]),
            ))
        steps_html = "\n".join(steps_parts) if steps_parts else "<p>기록된 단계 없음</p>"

        time_range = f"{self.start_time.strftime('%Y-%m-%d %H:%M:%S')} ~ {self.end_time.strftime('%H:%M:%S')}"

        return HTML_TEMPLATE.format(
            task_summary=_escape(self.task_summary),
            time_range=time_range,
            user=_escape(self.user) or "(미확인)",
            result_status=_escape(self.result_status),
            steps_html=steps_html,
            result_class="" if self.success else "result-fail",
            result_detail=self.result_detail,  # 이미 HTML일 수 있으므로 escape하지 않음
            generated_at=self.end_time.strftime("%Y-%m-%d %H:%M:%S"),
        )

    def save(self, path: str) -> str:
        """HTML 파일을 저장하고 경로를 반환한다."""
        html = self.render()
        p = Path(path)
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(html, encoding="utf-8")
        return str(p)

    def auto_save(self, output_dir: str) -> str:
        """타임스탬프 기반 파일명으로 자동 저장한다."""
        ts = datetime.now().strftime("%Y%m%d-%H%M%S")
        filename = f"iris-audit-{ts}.html"
        return self.save(str(Path(output_dir) / filename))


def _escape(text: str) -> str:
    """기본 HTML 이스케이프."""
    return (text
            .replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace('"', "&quot;"))


def main():
    parser = argparse.ArgumentParser(description="IRIS 감사 추적 HTML 생성")
    parser.add_argument("--json", required=True, help="감사 추적 단계 JSON 파일 경로")
    parser.add_argument("--output", required=True, help="출력 HTML 파일 경로")
    args = parser.parse_args()

    with open(args.json, "r", encoding="utf-8") as f:
        data = json.load(f)

    trail = AuditTrail(
        task_summary=data.get("task_summary", ""),
        user=data.get("user", ""),
    )

    for step in data.get("steps", []):
        trail.add_step(
            step_type=step.get("type", "info"),
            description=step.get("description", ""),
            timestamp=step.get("timestamp"),
        )

    result = data.get("result", {})
    trail.set_result(
        status=result.get("status", "완료"),
        detail=result.get("detail", ""),
        success=result.get("success", True),
    )

    out_path = trail.save(args.output)
    print(f"감사 추적 HTML 생성 완료: {out_path}")


if __name__ == "__main__":
    main()
